// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	database "chi-learn/internals/database"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateCompany provides a mock function with given fields: c, u
func (_m *Service) CreateCompany(c *database.Company, u *database.CreateUser) error {
	ret := _m.Called(c, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*database.Company, *database.CreateUser) error); ok {
		r0 = rf(c, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompany'
type Service_CreateCompany_Call struct {
	*mock.Call
}

// CreateCompany is a helper method to define mock.On call
//   - c *database.Company
//   - u *database.CreateUser
func (_e *Service_Expecter) CreateCompany(c interface{}, u interface{}) *Service_CreateCompany_Call {
	return &Service_CreateCompany_Call{Call: _e.mock.On("CreateCompany", c, u)}
}

func (_c *Service_CreateCompany_Call) Run(run func(c *database.Company, u *database.CreateUser)) *Service_CreateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*database.Company), args[1].(*database.CreateUser))
	})
	return _c
}

func (_c *Service_CreateCompany_Call) Return(_a0 error) *Service_CreateCompany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateCompany_Call) RunAndReturn(run func(*database.Company, *database.CreateUser) error) *Service_CreateCompany_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: email, password
func (_m *Service) Login(email string, password string) (database.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (database.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) database.User); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Service_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *Service_Expecter) Login(email interface{}, password interface{}) *Service_Login_Call {
	return &Service_Login_Call{Call: _e.mock.On("Login", email, password)}
}

func (_c *Service_Login_Call) Run(run func(email string, password string)) *Service_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Service_Login_Call) Return(_a0 database.User, _a1 error) *Service_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Login_Call) RunAndReturn(run func(string, string) (database.User, error)) *Service_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Migration provides a mock function with given fields:
func (_m *Service) Migration() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Migration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Migration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migration'
type Service_Migration_Call struct {
	*mock.Call
}

// Migration is a helper method to define mock.On call
func (_e *Service_Expecter) Migration() *Service_Migration_Call {
	return &Service_Migration_Call{Call: _e.mock.On("Migration")}
}

func (_c *Service_Migration_Call) Run(run func()) *Service_Migration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Migration_Call) Return(_a0 error) *Service_Migration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Migration_Call) RunAndReturn(run func() error) *Service_Migration_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
